### ISSUE TITLE
App keeps crashing when openning the base gallery

### ISSUE THREAD

**Issue by doryashar** [scubajeff/lespas#166]
**Bug description:**
The app crashes every time i go into "Gallery".
already tried to remove data, cache, remove and reinstall

**Screenshots:**
Added screen video in attachment:
https://github.com/scubajeff/lespas/assets/14197514/8da8e4ee-a6fb-44db-8f48-241671efa931

**Smartphone:**
 - Device: Samsung S21 Ultra
 - OS: Android 13
 - App Version 2.9.9

**Comment by scubajeff** [comment]
Do you have installed Les Pas from Google Play? If yes, I will see the crash log on my Play console. If not, you might need to somehow get the log and post it here, since Les Pas doesn't collect any log by itself.

Some wild guesses, are you using Samsung Knox? Is your phone's gallery protected by private folder? In your screen recording, I notice that album's cover won't show, is that album local or remote?

**Comment by doryashar** [comment]
I did install from Google play. 
I don't know Knox so I guess that I'm not using it. 
No protection of any kind. 
The app kept crashing so I tried many things. One of them is to create a new album. After adding the first photos,  I added some more and it created a new empty album with the same name. This is probably another bug but not related to the current one, since the issue happened even prior to having albums.

**Comment by scubajeff** [comment]
I will see what I could get from Google Play developer console.

**Comment by scubajeff** [comment]
By the way, are you using stock OS or customized ROM like Lineage?

**Comment by doryashar** [comment]
Stock OS

**Comment by scubajeff** [comment]
I got a few crash reports from Play Console, bit none of them is related to this issue. Honestly I don't really know under what circumstance and condition will crash be reported. Without the log, very little can be done on my side.

**Comment by doryashar** [comment]
I'm willing to assist.
How can I generate a log?

**Comment by scubajeff** [comment]
To read Android's log, you need a computer with `adb` installed or your phone must be rooted .

**Comment by muminpappa** [comment]
Just stumbled across this issue. I observe the same with v2.9.13. I first had this issue on my old phone. Now I switched to a new phone (Fairphone 5, e/OS/ 2.9) which I set up from scratch i.e. no backup / restore used. And I get the same issue again. Are there any new insights on this? 
I'll try to collect a log file. I have `adb` installed, just need to google how to do this.

**Comment by scubajeff** [comment]
@muminpappa Here's the steps to get the log:

1. Enable developer mode and USB debugging on your phone. https://developer.android.com/studio/debug/dev-options#enable
2. Connect your phone to your computer by using a USB cable
3. Type `adb` devices in your computer's command line. If you see a device being listed in the command output, you are set
4. Type `adb logcat -b crash` in your computer's command line
5. Run Les Pas on your phone and let it crash, you will see the crash log printed on your computer's screen. Cut and paste here the output

**Comment by muminpappa** [comment]
```
04-25 18:01:10.629 22151  1271 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
04-25 18:01:10.629 22151  1271 E AndroidRuntime: Process: site.leos.apps.lespas, PID: 22151
04-25 18:01:10.629 22151  1271 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlinx.coroutines.flow.MutableStateFlow.getValue()' on a null object reference
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at site.leos.apps.lespas.gallery.GalleryFragment$GalleryViewModel$1$1$1.invokeSuspend(GalleryFragment.kt:653)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at site.leos.apps.lespas.gallery.GalleryFragment$GalleryViewModel$1$1$1.invoke(Unknown Source:15)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at site.leos.apps.lespas.gallery.GalleryFragment$GalleryViewModel$1$1$1.invoke(Unknown Source:6)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:29)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Unknown Source:13)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Unknown Source:6)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:73)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
04-25 18:01:10.629 22151  1271 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a95c88, Dispatchers.IO]

```

**Comment by scubajeff** [comment]
@muminpappa Would you like to test a debug version of Les Pas? It involves some actions like these:

1. Uninstall your current installed Les Pas
2. Download the debug version from https://mega.nz/file/EmhxWa5D#hjFMCF7Y8BdQJzXrykuUeRHoIKSi6yzNFR_JpOdMJLw, then install it
3. Test
4. Uninstall the debug version and reinstall the release version from F-Droid.

**Comment by muminpappa** [comment]
So far, the debug version works w/o crashes. So I'll dwell at step 3 for a few days. Also before, the crashes did not start immediately but after using the app for about a week.

Awesome support from your side, I'm really grateful!

**Comment by scubajeff** [comment]
Actually this bug has been fixed a few releases before, though it was a fix to another issue. I re-introduced it in the last official update, silly me!
