### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by nikp123** [scubajeff/lespas#18]
**Describe the bug**
Crash after login.

**To Reproduce**
1. Install app
2. Log into server (past the Web UI and everything)
3. Oh no, crash!

**Expected behavior**
No crash after login.

**Screenshots**
"Les Pass keeps stopping" via the SystemUI process.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 5
 - OS: /e/ OS 3 based on Android 10 (Custom ROM)
 - Browser *default Chromium thing that ships with every Android*
 - Version 2.1.0

**Additional context**

ADB log:
```
--------- beginning of main
07-20 19:45:22.774 25663 25663 E eos.apps.lespa: Not starting debugger since process cannot load the jdwp agent.
07-20 19:45:22.832 25663 25663 W Riru64  : 99e3 is too old to hide so
07-20 19:45:27.312 25663 25663 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a20286f
07-20 19:45:27.540 25663 25663 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8ad57fe
07-20 19:45:27.882 25663 25663 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-20 19:45:27.886 25663 25663 E AndroidRuntime: FATAL EXCEPTION: main
07-20 19:45:27.886 25663 25663 E AndroidRuntime: Process: site.leos.apps.lespas, PID: 25663
07-20 19:45:27.886 25663 25663 E AndroidRuntime: java.lang.RuntimeException: Cannot create an instance of class site.leos.apps.lespas.publication.NCShareViewModel
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at site.leos.apps.lespas.album.AlbumFragment.getPublishViewModel(AlbumFragment.kt:54)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at site.leos.apps.lespas.album.AlbumFragment.onViewCreated(AlbumFragment.kt:108)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7847)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-20 19:45:27.886 25663 25663 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        ... 36 more
07-20 19:45:27.886 25663 25663 E AndroidRuntime: Caused by: java.lang.SecurityException: uid 10194 cannot get user data for accounts of type: com.google
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2071)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2039)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1987)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at android.accounts.AccountManager.getUserData(AccountManager.java:514)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        at site.leos.apps.lespas.publication.NCShareViewModel.<init>(NCShareViewModel.kt:88)
07-20 19:45:27.886 25663 25663 E AndroidRuntime:        ... 39 more
07-20 19:45:27.887 25663 25663 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-20 19:45:27.887 25663 25663 E AndroidRuntime:        at com.android.server.accounts.AccountManagerService.getUserData(Unknown Source:159)
07-20 19:45:27.887 25663 25663 E AndroidRuntime:        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
07-20 19:45:27.887 25663 25663 E AndroidRuntime:        at com.android.server.accounts.AccountManagerService.onTransact(Unknown Source:0)
07-20 19:45:27.887 25663 25663 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1021)
07-20 19:45:27.887 25663 25663 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:994)
07-20 19:45:27.887 25663 25663 E AndroidRuntime: 
```

NextCloud 21.0.3 running in Docker on ArchLinux

**Comment by nikp123** [comment]
ps. just noticed the 2.1.1 release, where can I download it at (without firing up Gradle or something silly like that)

**Comment by scubajeff** [comment]
Les Pas stores Nextcloud server login credential in system's account storage, which is accessed thru. Android's AccountManager API. Log indicates that there is a SecurityException just after Les Pas call getAccounts() to retrieve credentials. I know that /e/ is a privacy focus Android mod, seems to me it alters the AccountManager API or permission scheme. As I don't have a /e/ device, it's difficult to debug. Or could you point me to some place where there are documents on /e/'s modification. 

Latest is always available on Google Play. I also publish to F-droid at the same time, F-droid build pipeline will usually take 1 week to build. BTW, 2.1.1 will not fix this.

**Comment by nikp123** [comment]
>Android's AccountManager API. Log indicates that there is a SecurityException just after Les Pas call getAccounts() to retrieve credentials.

interestingly enough, no other app has this issue (maybe its one of the edge cases or other apps do have fixes for /e/ OS, though I doubt this). First thing I've checked the permissions and they were all denied by default, but even after enabling them and recreating the account, I still run into issues. Do you happen to access the NextCloud creds directly or it is that not allowed (I don't know how the accounts system works to be frank)

But in the meantime I'll try to track down (as you suggested) the changes in the AccountManager API to see if it has any leads.

**Comment by scubajeff** [comment]
In your system setting screen, do you see a "Accounts" session? Normal AOSP will have this menu, and you will find Les Pas in the list among other apps, like twitter, github etc if you installed them.

**Comment by scubajeff** [comment]
just pushed out 2.2.0. i replaced getAccount() call with more cautious getAccountByType(). hope it will fix this crash.

**Comment by nikp123** [comment]
Can confirm that this fixed the issue.
Thank you!
