### ISSUE TITLE
Sync error in large Media folder (13k Images)

### ISSUE THREAD

**Issue by DeveloperOl** [scubajeff/lespas#93]
**Describe the bug**
Lespas sync stopped working for a single folder for me for a while now. In LesPas itself I only get the error "Last Synchronization failed (0 Minutes ago)". All other folders sync perfectly fine. I checked my nextcloud instance but every file seems to be fine (including metadata JSONs).
I tried clearing all user data and reinitalizing lespas, which did not solve the issue.

**To Reproduce**
1. Create large media folder in lespas
2. Sync failes for this folder

**Expected behavior**
The sync should run when triggered.

**ScreenshotsLogcat**
Logcat output shows: `failed sync operation JobId=100195 ***/site.leos.apps.lespas.nc u0 [site.leos.apps.lespas.StubProvider] USER ExpectedIn=-21s STANDBY-EXEMPTED(TOP) Reason=10356, SyncResult: stats [ numIoExceptions: 1]` (not sure if this helps, but thats all I get).

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 12L
 - Version: LesPas v2.6.1

**Comment by scubajeff** [comment]
Among those 13k files, is there a very large one, like several GB in size?

> I checked my nextcloud instance but every file seems to be fine (including metadata JSONs).
Do you mean even for the folder that contains 13K files, the metadata JSON file is correct?

**Comment by DeveloperOl** [comment]
No, the largest file is 41MB. Some more debugging showed, that a PROPFIND on the folder takes ~20 seconds and is ~14mb in size. Maybe there are limitations in lespas which are exceeded by these numbers? (And yes, I am working on a Redis Cache for my nextcloud instance, but this will not happen before next year 😆 )

**Comment by scubajeff** [comment]
Is this folder a Les Pas album? or a folder within `DCIM`?

> I checked my nextcloud instance but every file seems to be fine (including metadata JSONs).

Do you mean even for the folder that contains 13K files, the metadata JSON file is correct?

**Comment by DeveloperOl** [comment]
Its a normal LesPas album which I created using the app. I do not have DCIM sync enabled.
The JSON in the album folder seems correct. There are no syntax problems.

**Comment by DeveloperOl** [comment]
The content in the json file is correct. The Folder has 136075 images, but only 13351 are indexed in the json.
But the thing is, the folder does not show up in the LesPas App at all. I can only see the folder in browser or on synced desktop devices.

**Comment by scubajeff** [comment]
So this is an album/folder you added on server side, Les Pas tried to sync it to your phone, the sync is run in a special background job called SyncAdapter, which android os will limit it's runtime in the background to no more than 30 minutes. That would give each file about 0.13 seconds to finish extracting the file's EXIF, obviously not enough.

Since there is no other background job tools available in Android that can run more than 30 minutes, I have to figure out a way to resume syncing before this can be fixed.

**Comment by DeveloperOl** [comment]
No, the album was originally created on phone and started failing sync there. Now I reset my lespas and folder does not show up at all. The sync fails after ~15~20 seconds.
From my experience, lespas is very good in resuming synchronizations, so I'd still guess it's the long propfind on the JSON. And I don't see any other requests than the propfind in my nextcloud logs.

**Comment by DeveloperOl** [comment]
Filtering SyncAdapter in LogCat results in:

```
[11-17 10:46:26.343 14419:14463 E/SyncAdapter:]
java.net.SocketTimeoutException: timeout
	at j7.s$c.j(Unknown Source:4)
	at j7.s$c.l(Unknown Source:8)
	at j7.q.g(SourceFile:30)
	at g7.c.b(SourceFile:3)
	at h7.b.a(SourceFile:193)
	at h7.f.b(SourceFile:144)
	at k8.l$c.a(SourceFile:103)
	at h7.f.b(SourceFile:144)
	at g7.a.a(SourceFile:100)
	at h7.f.b(SourceFile:144)
	at e7.a.a(SourceFile:1140)
	at h7.f.b(SourceFile:144)
	at h7.a.a(SourceFile:154)
	at h7.f.b(SourceFile:144)
	at h7.h.a(SourceFile:153)
	at h7.f.b(SourceFile:144)
	at k8.l$b.a(SourceFile:35)
	at h7.f.b(SourceFile:144)
	at g7.e.k(SourceFile:138)
	at k8.l.n(SourceFile:74)
	at k8.l.o(Unknown Source:1)
	at q8.z.m(SourceFile:4)
	at q8.z.onPerformSync(SourceFile:65)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)
```

**Comment by DeveloperOl** [comment]
Further Debugging shows:
```
2022-11-17 12:13:53.007 30621-7073/site.leos.apps.lespas E/SyncAdapter:: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at site.leos.apps.lespas.helper.OkHttpWebDav$_init_$lambda$3$$inlined$-addNetworkInterceptor$1.intercept(OkHttpClient.kt:1080)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at site.leos.apps.lespas.helper.OkHttpWebDav$_init_$lambda$3$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1080)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at site.leos.apps.lespas.helper.OkHttpWebDav.list(OkHttpWebDav.kt:203)
        at site.leos.apps.lespas.helper.OkHttpWebDav.list$default(OkHttpWebDav.kt:200)
        at site.leos.apps.lespas.sync.SyncAdapter.syncRemoteChanges(SyncAdapter.kt:1108)
        at site.leos.apps.lespas.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:103)
        at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)
```

**Comment by DeveloperOl** [comment]
Changing read and write timout to 120 seconds fixes this issue. Maybe it should be increased permanently or made configuratble in settings?
Line changed and locally tested: https://github.com/scubajeff/lespas/blob/94e997ece44e5984413e47ecb6864f2cce8b73f5/app/src/main/java/site/leos/apps/lespas/helper/OkHttpWebDav.kt#L62

**Comment by scubajeff** [comment]
Yes, Les Pas will resume uploading from phone. I will incorporate these timeout setting in future release.
